Updated Husky file

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,6 +1,8 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 echo "Running Typecheck and Linting..."
-npm run typecheck
-npm run lint
-echo "✅ All checks passed!"
+
+npm run typecheck && npm run lint && echo "✅ All checks passed!" || {
+  echo "❌ Typecheck or Linting failed. Please fix the issues before committing."
+  exit 1
+}
